import { DrawElement } from "./types";

export const DRAW_ELEMENTS: DrawElement[] = [
  {
    type: "line",
    start: [160, 470],
    end: [105, 525],
  },
  {
    type: "line",
    start: [160, 470],
    end: [215, 525],
  },
  {
    type: "line",
    start: [160, 105],
    end: [160, 470],
  },
  {
    type: "line",
    start: [160, 105],
    end: [365, 105],
  },
  {
    type: "line",
    start: [161, 175],
    end: [243, 106],
  },
  {
    type: "line",
    start: [365, 105],
    end: [365, 165],
  },
  {
    type: "circle",
    radius: 45,
    center: [365, 210],
  },
  {
    type: "line",
    start: [365, 255],
    end: [365, 400],
  },
  {
    type: "line",
    start: [365, 315],
    end: [305, 270],
  },
  {
    type: "line",
    start: [365, 315],
    end: [425, 270],
  },
  {
    type: "line",
    start: [365, 400],
    end: [420, 455],
  },
  {
    type: "line",
    start: [365, 400],
    end: [310, 455],
  },
];

export const KEYBOARD: string[] = [
  "q",
  "w",
  "e",
  "r",
  "t",
  "y",
  "u",
  "i",
  "o",
  "p",
  " ",
  "a",
  "s",
  "d",
  "f",
  "g",
  "h",
  "j",
  "k",
  "l",
  " ",
  "z",
  "x",
  "c",
  "v",
  "b",
  "n",
  "m",
];

export const WORDS: string[] = [
  "typescript",
  "pablo escobar",
  "programming",
  "zodiac sign",
  "game of thrones",
  "pulp fiction",
  "pablo picasso",
  "the united kingdom",
  "heavy metal",
  "corpus christi",
  "independence day",
  "old fashioned",
  "imagination",
  "fairy tale",
  "instant coffee",
  "sparkling water",
  "delightful",
  "reverse",
  "substantial",
  "computer games",
  "dairy products",
  "media player",
  "friendship",
  "happiness",
  "mountains",
  "jungle",
  "collect stamps",
  "marvel comics",
  "avengers",
  "word games",
  "weather forecast",
  "addiction",
  "file manager",
  "interface",
  "carol singing",
  "anniversary",
  "fortune is fickle",
  "haste makes waste",
  "the godfather",
  "harry potter",
  "fight club",
  "the lion king",
  "bohemian rhapsody",
];
